export const frases = [
  'Éxito',
  'Libertad',
  'Confianza',
  'Esperanza',
  'Valentía',
  'Felicidad',
  'Gratitud',
  'Generosidad',
  'Honestidad',
  'Lealtad',
  'Humildad',
  'Paciencia',
  'Perseverancia',
  'Empatía',
  'Inspiración',
  'Agradecimiento',
  'Pasión',
  'Optimismo',
  'Fuerza',
  'Resiliencia',
  'Motivación',
  'Autoestima',
  'Alegría',
  'Paz',
  'Entusiasmo',
  'Propósito',
  'Creatividad',
  'Aceptación',
  'Compasión',
  'Tolerancia',
  'Amabilidad',
  'Sabiduría',
  'Integridad',
  'Confianza en uno mismo',
  'Espiritualidad',
  'Fortaleza interior',
  'Amor propio',
  'Optimismo',
  'Comunicación',
  'Determinación',
  'Curiosidad',
]
